### ISSUE TITLE
Running EggCrack in Linux Debian Commandline - Error No X11 DISPLAY...

### ISSUE THREAD

**Issue by Jan2220** [Manevolent/EggCrack#28]
Hey,
Today i tried to start EggCrack with the Commandline on my Linux Debian Virtualserver.
But everytime i try to start EggCrack Check with command: `java -jar EggCrack.jar -check mcaccounts.txt -proxies proxies.txt -outputFile workingaccounts.txt`
This Error appears:

```
 Exception in thread "main" java.awt.HeadlessException:
 No X11 DISPLAY variable was set, but this program performed an operation which requires it.
         at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
         at java.awt.Window.init(Window.java:476)
         at java.awt.Window.<init>(Window.java:438)
         at java.awt.Window.<init>(Window.java:594)
         at java.awt.Dialog.<init>(Dialog.java:665)
         at javax.swing.JDialog.<init>(JDialog.java:590)
         at javax.swing.JDialog.<init>(JDialog.java:523)
         at com.teamlixo.eggcrack.Main.<init>(Main.java:61)
         at com.teamlixo.eggcrack.Main.main(Main.java:327)
```
 

How do i fix this?
Please help ^^

~Jan (Jan2220)

**Comment by Jan2220** [comment]
With the newest Version from github (2.0) it worked ^^ mpgh was outdated with 1.8

SOLVED
